// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1x29tv_q4Ac9kz7DPcH1HK7-jkCyuLQA',
    appId: '1:381804236275:web:3908ef824096c486131686',
    messagingSenderId: '381804236275',
    projectId: 'sotkonya-42',
    authDomain: 'sotkonya-42.firebaseapp.com',
    storageBucket: 'sotkonya-42.firebasestorage.app',
    measurementId: 'G-3SPXV8HC31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5xM-T6g3pCri-v4SlKqYrGR_s1rldcpA',
    appId: '1:381804236275:android:887a36476e323bd9131686',
    messagingSenderId: '381804236275',
    projectId: 'sotkonya-42',
    storageBucket: 'sotkonya-42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBclApUp3DWnWumTzzBLdSza_LS48S2Lc',
    appId: '1:381804236275:ios:e371124c937a9aae131686',
    messagingSenderId: '381804236275',
    projectId: 'sotkonya-42',
    storageBucket: 'sotkonya-42.firebasestorage.app',
    iosBundleId: 'com.example.sotkonya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBclApUp3DWnWumTzzBLdSza_LS48S2Lc',
    appId: '1:381804236275:ios:e371124c937a9aae131686',
    messagingSenderId: '381804236275',
    projectId: 'sotkonya-42',
    storageBucket: 'sotkonya-42.firebasestorage.app',
    iosBundleId: 'com.example.sotkonya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1x29tv_q4Ac9kz7DPcH1HK7-jkCyuLQA',
    appId: '1:381804236275:web:28eef147515f8021131686',
    messagingSenderId: '381804236275',
    projectId: 'sotkonya-42',
    authDomain: 'sotkonya-42.firebaseapp.com',
    storageBucket: 'sotkonya-42.firebasestorage.app',
    measurementId: 'G-2X7HN6YX8W',
  );
}
